- app/src/routes/account/profile/create/+page.svelte
- cloudfunctions/collect_examples/emails.go
- cloudfunctions/email_push_notifications/emails.go
- cloudfunctions/full_email_sync/emails.go
- libs/gmail/label.go
Change to follow the same blue colors scheme we are using on the website. This will likely change again in the future. Also renames vars to be more idiomatic Go without the `_`
> style: update gmail label colors

- cloudfunctions/email_push_notifications/classifier.go
- cloudfunctions/email_push_notifications/classifier_test.go
- cloudfunctions/email_push_notifications/sync.go
- cloudfunctions/full_email_sync/classifier.go
- cloudfunctions/full_email_sync/cloudfunction.go
- libs/gmail/fwd.go
- libs/gmail/go.mod
- libs/gmail/go.sum
- libs/gmail/messages.go
Updates the interface for the classifier to take in the email in a generic (from, subject, body) form. Pushes the reprocess to the model.
Delaying moving the classifier client/interface into `/libs` for a little longer...
- refactor: simplify messages api
- feat: switch to new v1 model interface
> refactor: move to new v1 classifier API

- cloudfunctions/email_push_notifications/cloudfunction.go
- cloudfunctions/email_push_notifications/sync.go
- cloudfunctions/full_email_sync/cloudfunction.go
- libs/gmail/clone.go
Use Gmail's `insert` API to "clone" a message from a source inbox to a destination inbox.
This is better for collecting examples because it preserves the original message headers and format. It also doesn't create new messages in the user's inbox history, which we then later have to process.
> Insert Emails to Collect Rather than Fwd

- .github/workflows/ci.yml
- cloudfunctions/adhoc/README.md
- cloudfunctions/adhoc/go.mod
- cloudfunctions/adhoc/migrate_labels.go
- go.work
- scripts/update-go-mods.sh
This workflow
1. Gets all messages that match the old label scheme, but not the current one
2. Removes `@SRC` from the message labels
3. Deletes the old `@SRC/Job Opportunity` label
4. Update the settings of the `@SRC` to match the new one
Adds the new `adhoc` package to CI
> Adhoc Cloud Function for Migrating Users to New Label Scheme

- .github/workflows/auto-assign.yml
Auto assign failed to run on https://github.com/shared-recruiting-co/shared-recruiting-co/pull/58 because it references `GITHUB_TOKEN`.
This runs it in the context of the base branch (`pull_request_target`), allowing it to run on PRs from forked repos.
> fix: run auto assign in context of base fork

- cloudfunctions/email_push_notifications/cloudfunction.go
- cloudfunctions/full_email_sync/cloudfunction.go
- cloudfunctions/watch_emails/cloudfunction.go
Add `ServerName` to distinguish between which cloud function the error originated. 
I accidentally pushed the sentry implementation commits to main, but I'm going to deploy the changes to production before merging. Once confirmed working, I will merge this PR
Closes #51
> feat: add server name for error tracking

- app/supabase/migrations/20230110015803_cascade_user_delete.sql
- libs/db/schema.sql
Relates to #60
To make user database data deletion, trivial we can enable cascading deletes on all `user_id` foreign key relationships.
> feat: cascade user deletes to make account deletion trivial

- libs/gmail/gmail.go
- libs/gmail/message.go
- libs/gmail/message_test.go
Relates to #50
Adds helper functions for working with threads and messages. Finally adds unit tests for `message.go`. We should consider moving messages to `/libs/gmail/message/` to avoid the redundant `MessageXXX` prefix on each function.
> feat(gmail): Add Thread and Message Helpers

- cloudfunctions/adhoc/main.go
- cloudfunctions/adhoc/migrate_labels.go
- cloudfunctions/adhoc/ml.go
- cloudfunctions/adhoc/populate_jobs.go
- libs/gmail/message.go
- libs/gmail/message_test.go
Relates to #69
Creates a manually executed cloud function for iterating through labeled emails and attempting to parse jobs from them. If the ML service is able to parse it, the job is saved for the current user in the database. 
Once this is up and running, we will "productionize" it by parsing jobs in real-time as jobs are labeled with `@SRC`.
I was tempted to, but held off refactoring the `/libs` directory. I will make a ticket to refactor into a single package with the ml client. (Follow up tickets #78 #79)
> Ad-hoc Cloud Function for Parsing Emails into Jobs

- app/src/lib/components/ConnectGoogleAccountButton.svelte
- app/src/routes/(app)/account/create/+page@.svelte
- app/src/routes/api/account/gmail/connect/+server.ts
Require a client-side check for terms of service before connecting Gmail account. Technically users are already prompted in the native Google Auth modal already, but this makes it more clear. 
In the future, we can decide to persist this database side.
> feat: require users to check terms of service before signing up

- cloudfunctions/full_email_sync/cloudfunction.go
- cloudfunctions/full_email_sync/email.go
- deploy/cloudfunction.go
Closes #101
Migrates the full email sync handler to push messages to the candidate message handler. Add support for "dry runs" where we make predictions, but do not update labels.
> Async Message Handling for Full Sync

- cloudfunctions/email_push_notifications/cloudfunction.go
- libs/src/db/models.go
- libs/src/db/query.sql
- libs/src/db/query.sql.go
- libs/src/db/schema.sql
- libs/src/go.mod
- libs/src/go.sum
- web/src/lib/supabase/types.ts
- web/supabase/migrations/20230216145636_multi_inbox_type_user_email_sync.sql
Relates to #111
Relates to #49
In theory, a user can be a recruiter and a candidate. This allows the same email to be tracked in `user_email_sync_history` but we can progress the sync history independently.
Adding `email` to the table is a step towards supporting #49
This is the first of several migration PRs. Once `email` is lazily initialized, we will make it `not null` and update the table primary key to `(user_id, email, inbox_type)`
> feat: Track Recruiter Email Sync History Independently

- cloudfunctions/email_push_notifications/cloudfunction.go
- libs/src/db/http.go
- libs/src/db/models.go
- libs/src/db/querier.go
- libs/src/db/query.sql
- libs/src/db/query.sql.go
- libs/src/db/schema.sql
- libs/src/go.mod
- libs/src/go.sum
- web/src/lib/supabase/types.ts
- web/supabase/migrations/20230218000412_multi_inbox_user_email_sync_pk.sql
Relates to #49
Updates the primary key to be `(user_id, inbox_type, email)`. This will let us track recruiter email sync history on the same table and supports multiple emails per inbox.
> Update User Email Sync History PK

- deploy/.golangci.yml
- deploy/cloudfunction.go
- deploy/cloudfunction_test.go
Relates to #92
Deploys separate gmail push notification handlers in parallel with the existing `email_push_notification`.
> Deploy Separate Gmail Push Notification Handlers

- libs/src/mail/gmail/gmail.go
- libs/src/mail/gmail/label/candidate.go
- libs/src/mail/gmail/label/label.go
- libs/src/mail/gmail/label/recruiter.go
Recruiters need different labels to candidates. This starts making a distinction. Will follow up with a PR to migrate all of the existing call sites.
> Create Separate @SRC Labels for Recruiters

- cloudfunctions/adhoc/reclassify.go
- cloudfunctions/adhoc/unsubscribe.go
- cloudfunctions/candidate_email_sync/cloudfunction.go
- cloudfunctions/candidate_gmail_messages/cloudfunction.go
- cloudfunctions/candidate_gmail_push_notifications/cloudfunction.go
- cloudfunctions/gmail_subscription/cloudfunction.go
- cloudfunctions/populate_jobs/cloudfunction.go
- cloudfunctions/recruiter_email_sync/cloudfunction.go
- cloudfunctions/recruiter_gmail_push_notifications/cloudfunction.go
- libs/src/db/models.go
- libs/src/db/query.sql
- libs/src/db/query.sql.go
- libs/src/db/schema.sql
- libs/src/go.mod
- libs/src/go.sum
- web/src/lib/supabase/types.ts
- web/supabase/migrations/20230220235803_add_email_to_user_oauth_token.sql
Relates to #49
Adds an `email` column to the `user_oauth_token` table. Next we need to populate the field, then update all the Get callsites to include email in the request.
> Add Email to User OAuth Token Table

- cloudfunctions/adhoc/populate_jobs.go
- cloudfunctions/adhoc/reclassify.go
- cloudfunctions/adhoc/unsubscribe.go
- cloudfunctions/candidate_email_sync/cloudfunction.go
- cloudfunctions/candidate_gmail_messages/cloudfunction.go
- cloudfunctions/candidate_gmail_push_notifications/cloudfunction.go
- cloudfunctions/populate_jobs/cloudfunction.go
- cloudfunctions/recruiter_email_sync/cloudfunction.go
- cloudfunctions/recruiter_gmail_messages/cloudfunction.go
- cloudfunctions/recruiter_gmail_push_notifications/cloudfunction.go
- libs/src/db/http.go
- libs/src/db/models.go
- libs/src/db/query.sql
- libs/src/db/query.sql.go
- libs/src/db/schema.sql
- libs/src/go.mod
- libs/src/go.sum
- web/src/lib/server/google/gmail.ts
- web/src/lib/supabase/types.ts
- web/src/routes/api/account/gmail/connect/+server.ts
- web/supabase/migrations/20230221003612_multi_email_user_oauth_token_pk.sql
Relates to #49
- Updates the PK of `user_oauth_token` to allow for multiple emails per user and provider. 
- Updates references in Cloud Functions
This doesn't update the frontend, so from end-users perspectives nothing has changed.
> Support Multiple Emails per Account (Backend)

- web/src/routes/(app)/recruiter/(account)/jobs/[id]/+page.svelte
- web/src/routes/(app)/recruiter/(account)/jobs/[id]/+page.ts
- web/src/routes/(app)/recruiter/(account)/jobs/[id]/Candidates.svelte
- web/src/routes/(app)/recruiter/(account)/jobs/[id]/OutboundTemplates.svelte
Adds a simple empty state for the two tabs on the candidate page. Also uses promise.all to parallelize data loading
> Add Empty States to Job Details Page

- web/supabase/tests/database/0_setup.test.sql
- web/supabase/tests/database/canary.test.sql
There is no native setup functionality, but currently Supabase or pgTap loads files alphabetically. We take advantage of that by prefixing the file with `0_`
Credit to https://blog.mansueli.com/using-custom-claims-testing-rls-with-supabase#heading-using-the-helpers-to-simulate-login-and-rls-policies for the auth helper functions
> feat: init helper test functions for pgTap

- cloudfunctions/candidate_gmail_push_notifications/email.go
- cloudfunctions/candidate_gmail_push_notifications/sync.go
- libs/src/pubsub/schema/schema.go
Prep for bidirectional sync logic. In order for us to sync labels between gmail and the DB, we need to know when `@SRC` labels are removed or added.
This adds placeholder logic to publish email label changes to a separate topic for handling.
> feat: fetch email label changes from history

- cloudfunctions/candidate_gmail_label_changes/cloudfunction.go
- cloudfunctions/candidate_gmail_messages/cloudfunction.go
- libs/src/db/db.go
- libs/src/db/http.go
- libs/src/db/querier.go
- libs/src/db/query.sql
- libs/src/db/query.sql.go
- refactor: handle job opportunities on label add
- chore: remove unused service
- fix: use payload email not profile email
- feat: add query for deleting user_email_job by (user_email, thread_id)
- feat: delete user_email_job when gmail label is removed
Delete the corresponding entry to `user_email_job` when the `@SRC/Jobs/Opportunity` label is removed.
> Remove User Email Job When Gmail Label is Removed

- web/src/routes/(app)/account/jobs/+page.svelte
Relates to #209
Simple icons to indicate job interest. I still need to
1) Create the interest Gmail labels
2) Make icon buttons functional (upsert DB, update gmail labels)
3) Remove interest when `user_email_job` entry is deleted
4) Table filters or tabs
> style: simple icons for job interest

- cloudfunctions/candidate_gmail_messages/cloudfunction.go
- libs/src/mail/gmail/gmail.go
- libs/src/mail/gmail/label/candidate.go
- Addresses: https://github.com/shared-recruiting-co/shared-recruiting-co/issues/226
- Adds a `JobsVerified` label for emails that come from outbound SRC recruiting emails
- Label is added in the `processMessages` function of [cloudfunctions/candidate_gmail_messages/cloudfunction.go](https://github.com/shared-recruiting-co/shared-recruiting-co/compare/main...msteinbrick:shared-recruiting-co:add-verified-labels-for-official-jobs?expand=1#diff-ed0bb4e4a7e4cc1d87c8bf9863805db8e3e01713e3f3286aaaf6e6a1fdd80dd4)
- No additional bi-directional sync logic added
- Users do not have the ability to remove verified labels in the UI, unlike the Interested / Uninterested / Saved labels
- If a user removes a Jobs/Verified label from an email, there is no action to be taken on the DB side
@devstein - let …
> Add Verified Label to Known Recruiting Emails
