- cloudfunctions/email_push_notifications/cloudfunction.go
> feat: use multiple labels with @SRC top-level label

- app/src/app.css
- app/tailwind.config.cjs
> feat: Use miriam libre as default font

- libs/gmail/fwd.go
Forwarding an email with the gmail API is surprisingly complicated. Every email client has their own unique way of generating a forwarded email for users. This is a simplified version of the Gmail client's version of forwarding emails.
> Forward Email Function

- cloudfunctions/collect_examples/cloudfunction.go
- cloudfunctions/collect_examples/emails.go
- cloudfunctions/email_push_notifications/cloudfunction.go
- cloudfunctions/new_user_workflow/cloudfunction.go
- libs/gmail/fwd.go
- libs/gmail/label.go
Share label get/create logic between cloud funcitons
> Refactor Label Get/Create Logic

- cloudfunctions/watch_emails/cloudfunction.go
Use the `include` LabelFilterAction when watching for new unread emails
> feat: only watch for new unread messages

- app/package-lock.json
- app/package.json
- app/src/routes/join/+page.svelte
> style: add confetti

- cloudfunctions/collect_examples/cloudfunction.go
- cloudfunctions/collect_examples/emails.go
- cloudfunctions/email_push_notifications/cloudfunction.go
- cloudfunctions/email_push_notifications/emails.go
- cloudfunctions/email_push_notifications/sync.go
- cloudfunctions/full_email_sync/cloudfunction.go
- cloudfunctions/full_email_sync/emails.go
- cloudfunctions/watch_emails/cloudfunction.go
- libs/gmail/fwd.go
- libs/gmail/gmail.go
- libs/gmail/label.go
Creates a wrapper `Service` struct for convenience methods and caching. Updates references in cloud functions.
- refactor: create wrapper service
- refactor: update cloudfunctions to use new api
> refactor(gmail): add wrapper service struct

- libs/db/client/models.go
- libs/db/go.mod
- libs/db/go.sum
- chore: go mod tidy
- chore: run `sqlc generate`
> Re-Generate DB Client

- .github/workflows/ci.yml
- app/.prettierrc
- app/package.json
- app/src/lib/components/Header.svelte
- app/src/lib/supabase/types.ts
- app/src/routes/account/profile/+page.svelte
- cloudfunctions/collect_examples/cloudfunction.go
- cloudfunctions/email_push_notifications/cloudfunction.go
- cloudfunctions/email_push_notifications/sync.go
- cloudfunctions/full_email_sync/cloudfunction.go
- cloudfunctions/watch_emails/cloudfunction.go
- libs/db/client/http.go
- libs/db/sqlc.yaml
Last of a series of PRs.  See #25 for rationale.
> Use PostgREST Client in Cloud Functions

- cloudfunctions/email_push_notifications/cloudfunction.go
- cloudfunctions/email_push_notifications/go.mod
- cloudfunctions/email_push_notifications/go.sum
- cloudfunctions/email_push_notifications/sync.go
- cloudfunctions/full_email_sync/cloudfunction.go
- cloudfunctions/full_email_sync/go.mod
- cloudfunctions/full_email_sync/go.sum
- cloudfunctions/watch_emails/cloudfunction.go
- cloudfunctions/watch_emails/go.mod
- cloudfunctions/watch_emails/go.sum
- libs/gmail/gmail.go
- Do not trigger `watch` if user's email is deactivated
- Auto Archive = Remove "UNREAD" and "INBOX" labels
- Auto Contribute = Forward to examples@sharedrecruiting.co
- feat: do not watch emails that are deactivated
- feat: refactor recruiting email handling, add auto archive functionality
- chore: add comment for future
- feat: use auto_archive and auto_contribute in sync handlers
- chore: go mod update
> Use Email Settings in Cloud Functions

- app/src/routes/account/profile/+page.svelte
- app/src/routes/account/profile/+page.ts
- app/src/routes/account/profile/create/+page.svelte
- app/src/routes/login/+page.svelte
Allow users to reconnect their gmail account if their oauth token is invalidated
- chore: remove stale comments
- feat: allow users to reconnect accounts if oauth token is invalidated
- feat: display login errors
> Allow Users to Reconnect Gmail Account

- app/src/routes/account/profile/+page.svelte
- app/src/routes/account/profile/+page.ts
- app/src/routes/account/profile/create/+page.svelte
- app/supabase/migrations/20221220010732_enable_realtime.sql
Adds user stats (synced at, emails processed, jobs detected) to the top of the user page. Follow up PRs implement this feature. This UI only
> [UI] Add User "Stats" to  Account Page

- cloudfunctions/email_push_notifications/cloudfunction.go
- cloudfunctions/email_push_notifications/sync.go
- cloudfunctions/full_email_sync/cloudfunction.go
- cloudfunctions/full_email_sync/emails.go
Start writing the new label scheme in cloud functions
> feat: Use New Label Scheme

- cloudfunctions/adhoc/migrate_labels.go
- cloudfunctions/email_push_notifications/cloudfunction.go
- cloudfunctions/email_push_notifications/sync.go
- cloudfunctions/full_email_sync/cloudfunction.go
- cloudfunctions/watch_emails/cloudfunction.go
- libs/gmail/clone.go
- libs/gmail/errors.go
- libs/gmail/gmail.go
- libs/gmail/go.mod
- libs/gmail/go.sum
Retries all requests in the `gmail` package using the `backoff` package. Yay for generics.
Also creates an error helpers.
> Retry Gmail Requests on 429 Errors

- libs/gmail/errors.go
- libs/gmail/errors_test.go
The first of many PRs to increase test coverage
> Tests for libs/gmail/errors

- README.md
First of several PRs to improve documentation in the repository.
> feat: Improve README

- app/src/app.d.ts
- app/src/error.html
- app/src/hooks.server.ts
- app/src/lib/components/PageError.svelte
- app/src/routes/(app)/account/+error.svelte
- app/src/routes/(marketing)/+error.svelte
- app/src/routes/+error.svelte
- app/src/routes/docs/+error.svelte
Adds simple custom error pages. This is a base to improve upon.
In the next PR, I'll add error tracking with Sentry
Relates to #51
> Basic Error Pages

- app/package-lock.json
- app/package.json
- app/src/hooks.server.ts
Add [Sentry](https://docs.sentry.io/platforms/node/) for server-side error tracking. Let's ignore client-side errors for now...next will be tracking errors in the cloud functions
Relates to #51
> feat: add sentry for server-side errors

- app/src/lib/supabase/client.server.ts
- app/src/routes/(app)/account/Sidenav.svelte
- app/src/routes/(app)/account/settings/+page.svelte
- app/src/routes/(app)/account/settings/DeleteAccountModal.svelte
- app/src/routes/api/account/+server.ts
- app/src/routes/api/account/delete.ts
- go.work.sum
Closes #60
Allows users to delete their own account without needing to contact us. Tested this manually locally.
> Allow Users to Delete Account within App

- app/src/routes/(app)/account/jobs/+page.svelte
- app/src/routes/(app)/account/jobs/+page.ts
- app/src/routes/(app)/account/profile/+page.svelte
Relates to #69
Creates a simple, mobile friendly jobs table for the user's personalized job board. Nest steps are
1. Create the jobs schema
2. Create a job to parse job emails and populate it
Also includes a refactor on profile to use `PageData` for better type support.
> Jobs Table UI

- cloudfunctions/adhoc/ml.go
- cloudfunctions/adhoc/populate_jobs.go
Relates to #69
Some fixes for the parse job manual workflow. I've already deployed these fixes to production.
> Parse Job Fixes

- app/src/routes/(app)/account/jobs/+page.svelte
- app/src/routes/(app)/account/jobs/+page.ts
Fetch and display jobs from Supabase. Add a useful page description and empty state.
> Populate Jobs Table from DB

- .github/workflows/ci.yml
- cloudfunctions/adhoc/main.go
- cloudfunctions/adhoc/populate_jobs.go
- cloudfunctions/adhoc/reclassify.go
- cloudfunctions/email_push_notifications/sync.go
- cloudfunctions/full_email_sync/cloudfunction.go
- cloudfunctions/full_email_sync/email.go
- cloudfunctions/populate_jobs/cloudfunction.go
- libs/src/db/http.go
- libs/src/db/http_test.go
- libs/src/mail/gmail/gmail.go
Fixes #73
Add [golangci](https://golangci-lint.run/) to CI
> Add golangci-lint to CI

- app/package-lock.json
- app/package.json
- app/src/routes/+layout.svelte
Closes #56
Use Vercel for privacy focused analytics for now. It's a basic, cost effective alternative to Fathom and Plausible.
> feat: use vercel for privacy focused analytics

- README.md
- app/package-lock.json
- app/package.json
- app/src/routes/+layout.svelte
- cloudfunctions/watch_emails/cloudfunction.go
- deploy/cloudfunction.go
Closes #53
Paginate over all candidates in the `watch_emails` job. We will handle recruiters separately in the future,
> Paginate Over All Candidates in Watch Job

- deploy/cloudfunction.go
- deploy/main.go
- deploy/pubsub.go
Relates to #101
This will make it easy to add more topics that are referenced by multiple CFs
> refactor: add Topics to infra struct

- deploy/cloudfunction.go
- deploy/main.go
- deploy/pubsub.go
Relates to #101
Creates a new topic for the push handler and full email sync handler to push messages to for processing
> Create Candidate Gmail Messages Topic

- cloudfunctions/watch_emails/cloudfunction.go
- deploy/cloudfunction.go
Refactor watch emails to prep for having two jobs one for candidates and one for recruiters.
> Refactor Watch Emails

- libs/src/pubsub/schema/schema.go
Relates to #101
Creates a shared lib for pubsub message schemas
> feat: add pubsub/schema shared library for message types

- cloudfunctions/candidate_gmail_messages/cloudfunction.go
- cloudfunctions/email_push_notifications/cloudfunction.go
- cloudfunctions/email_push_notifications/sync.go
- deploy/cloudfunction.go
- go.work.sum
Relates to #101
Start pushing messages to the placeholder candidate gmail message handler. Once we verify this is working, we'll cut the logic over.
> PoC: Push Messages from Notification to New Gmail Handler

- libs/src/mail/gmail/errors.go
- libs/src/mail/gmail/errors_test.go
Higher throughput = more requests.
Support all usage limit errors: https://developers.google.com/gmail/api/guides/handle-errors#resolve_a_403_error_usage_limit_exceeded
> feat: support more rate limit errors

- cloudfunctions/email_push_notifications/cloudfunction.go
- cloudfunctions/email_push_notifications/email.go
- cloudfunctions/email_push_notifications/sync.go
Use a `CloudFunction` struct to pass around state between functions. This will help us add additional logic in the future (for recruiters and labeled emails).
> refactor: push notification handler cleanup

- cloudfunctions/populate_jobs/cloudfunction.go
This job failed recently due to the new pagination params. This is a temporary fix until populate jobs is refactoring in the coming weeks.
> fix: update populate jobs to list candidate oauth tokens

- cloudfunctions/candidate_gmail_push_notifications/cloudfunction.go
- deploy/cloudfunction.go
- deploy/main.go
- deploy/pubsub.go
Per title! Migrate to candidate/recruiter specific topics
> Delete Old Gmail Topic

- cloudfunctions/adhoc/migrate_labels.go
- cloudfunctions/adhoc/reclassify.go
- cloudfunctions/candidate_email_sync/cloudfunction.go
- cloudfunctions/candidate_gmail_messages/cloudfunction.go
- cloudfunctions/candidate_gmail_push_notifications/cloudfunction.go
- cloudfunctions/recruiter_email_sync/cloudfunction.go
- cloudfunctions/recruiter_gmail_push_notifications/cloudfunction.go
- libs/src/mail/gmail/gmail.go
- libs/src/mail/gmail/label/label.go
Follow up from #127
Relates to #92
Use the new candidate/recruiter specific label functions
> Use Candidate/Recruiter Specfic @SRC Labels

- libs/src/db/schema.sql
- web/supabase/migrations/20230221145139_unique_email_provider.sql
Prevent multiple users from connecting them same accounts.
> Allow Only One Email/Provider

- libs/src/db/query.sql
- libs/src/db/query.sql.go
- libs/src/db/schema.sql
- web/supabase/migrations/20230221003612_multi_email_user_oauth_token_pk.sql
Per title. Make sure only one row is returned. Manually updated the functions in Supabase.
> fix: only return one user when getting by email

- libs/src/db/db.go
- libs/src/db/http.go
- libs/src/db/http_test.go
- libs/src/db/models.go
- libs/src/db/querier.go
- libs/src/db/query.sql
- libs/src/db/query.sql.go
- libs/src/db/schema.sql
Relates to #92
Relates to #93
An initial attempt at the schema to import recruiter outbound sequences into SRC. I'm going to avoid generating the Supabase migration until the handler implemented and most schema issues are worked out.
> Initial Recruiter Outbound Schema

- web/package-lock.json
- web/package.json
Updates to 1.8: https://svelte.dev/blog/streaming-snapshots-sveltekit
> chore: upgrade sveltekit

- libs/src/ml/ml.go
Updating the ml lib to reflect upcoming changes to the parse API.
> refactor: change JSON keys on ParseJobResponse

- libs/src/db/schema.sql
Relates to #93
Creates a table `candidate_company_inbound` to test linking outbound sequences to candidates even if the candidate isn't on the platform yet. This table is likely to change in the future, but is a useful proof of concept. It uses triggers to auto-populate and maintain the table.
> Use Triggers to Populate Jobs Table for Candidates from Outbound

- .github/workflows/ci.yml
- README.md
- libs/src/db/schema.sql
- web/src/lib/supabase/types.ts
- web/supabase/migrations/20230224214941_candidate_company_inbound.sql
- web/supabase/tests/database/canary.test.sql
- web/supabase/tests/database/candidate_company_inbound.test.sql
Relates to #93
Install `pgtap` and writes tests for the complex triggers that populate and maintain `candidate_company_inbound`
> test: Candidate Company Inbound Triggers

- web/package-lock.json
- web/package.json
> chore(deps): upgrade svelte(kit)

- libs/src/db/models.go
- libs/src/db/query.sql
- libs/src/db/query.sql.go
- libs/src/db/schema.sql
- web/src/lib/supabase/types.ts
- web/supabase/migrations/20230321020417_recruiter_email_settings.sql
- feat: add email settings to recruiter table
- chore(db): run supabase migration and type gen
- chore(db): run sqlc generate
> (2/4) feat(db): Add Recruiter Email Settings to DB

- web/src/routes/(app)/recruiter/(account)/Sidenav.svelte
- web/src/routes/(app)/recruiter/(account)/outbound/+page.svelte
- web/src/routes/(app)/recruiter/(account)/outbound/+page.ts
- web/src/routes/(app)/recruiter/(account)/profile/+page.svelte
Closes #162
Closes #163
Create an initial "outbound" page (naming tbd) for recruiters to see their outbound emails. Allows them to assign or un-assign a template to a job.
> feat(recruiter): Initial Outbound Template / Sequences Page

- libs/src/db/schema.sql
- web/supabase/migrations/20230224214941_candidate_company_inbound.sql
- web/supabase/tests/database/candidate_company_inbound.test.sql
A (hopefully) temporary fix to give recruiters permission to update job_id in the `candidate_company_inbound` table
> fix(db): allow recruiters to update job_id in trigger

- libs/src/db/schema.sql
- web/src/lib/supabase/types.ts
- web/src/routes/(app)/recruiter/(account)/jobs/+page.svelte
- web/src/routes/(app)/recruiter/(account)/jobs/+page.ts
- web/src/routes/(app)/recruiter/(account)/jobs/new/+page.server.ts
- web/src/routes/(app)/recruiter/(account)/outbound/+page.svelte
- web/src/routes/(app)/recruiter/(account)/outbound/+page.ts
- web/src/routes/(app)/recruiter/(account)/profile/GmailIntegration.svelte
- web/supabase/migrations/20230323013250_candidate_count_views.sql
Closes #164
First pass on candidate counts for jobs and sequences...will clean up code later 🙃
> feat(recruiter): show number of candidates per job and per outbound sequence

- web/src/lib/components/Hint.svelte
- web/src/lib/forms.ts
- web/src/lib/supabase/client.ts
- web/src/routes/(app)/account/profile/+page.svelte
- web/src/routes/(app)/account/profile/EmailSettings.svelte
- web/src/routes/(app)/recruiter/(account)/profile/GmailIntegration.svelte
Relates to #49
Users the same expandable settings pattern from the recruiter profile page. This will make it easier to display multiple connected accounts.
> Refactor User Email Settings UI

- libs/src/db/schema.sql
- web/src/lib/forms.ts
- web/src/lib/supabase/client.ts
- web/src/lib/supabase/types.ts
- web/src/routes/(app)/account/profile/+page.svelte
- web/src/routes/(app)/account/profile/+page.ts
- web/src/routes/(app)/account/setup/+page@.svelte
- web/src/routes/(app)/recruiter/login/+page.svelte
- web/src/routes/(app)/recruiter/setup/+page.svelte
- web/src/routes/(marketing)/Header.svelte
- web/src/routes/docs/Header.svelte
- web/supabase/migrations/20230327212631_candidate_job_count.sql
Relates to #191
Candidates have two categories of jobs:
1. (Unofficial) Inbound Jobs
2. (Official) SRC Verified Jobs
Updates the states at the top of the user page to reflect this.
> Display Candidate Job Counts

- libs/src/db/schema.sql
- web/supabase/migrations/20230327212631_candidate_job_count.sql
Per title. Manually fix the migration in Supabase.
> fix: do not show job counts for null candidates

- web/src/routes/(app)/account/jobs/+page.svelte
- web/src/routes/(app)/account/jobs/+page.ts
Relates to #161
Preps the UI to display verified jobs differently to inbound jobs. The follow up PR will create a new view of jobs that the job board will pull from
> style: add basic ui support for 'verified' jobs

- cloudfunctions/candidate_gmail_messages/cloudfunction.go
- Fixes known recruiting emails not getting labeled
- Removes deprecated `jobs_detected` metric
- Refactors classification and parsing
> Label Known Recruiting Emails and Small Refactor

- cloudfunctions/candidate_gmail_push_notifications/cloudfunction.go
- cloudfunctions/candidate_gmail_push_notifications/email.go
- cloudfunctions/candidate_gmail_push_notifications/sync.go
Filter out system label changes.
> feat: filter out system label changes

- .github/workflows/ci.yml
- cloudfunctions/candidate_gmail_label_changes/README.md
- cloudfunctions/candidate_gmail_label_changes/cloudfunction.go
- cloudfunctions/candidate_gmail_label_changes/go.mod
- cloudfunctions/candidate_gmail_push_notifications/email.go
- cloudfunctions/candidate_gmail_push_notifications/sync.go
- go.work
- libs/src/pubsub/schema/schema.go
- scripts/update-go-mods.sh
Initializes a placeholder function for handling candidate gmail label changes
> Initialize Candidate Gmail Label Changes Cloud Function

- deploy/cloudfunction.go
Grant permission to the push notification handler to publish to the new topic.
> fix: grant publish permission

- cloudfunctions/candidate_gmail_label_changes/cloudfunction.go
Placeholder logic for handling job opportunity label's getting added or removed.
This code is ugly AF. I'm not sure what the best go pattern is for this.
> Placeholder Label Handlers

- cloudfunctions/candidate_gmail_label_changes/cloudfunction.go
- cloudfunctions/candidate_gmail_messages/cloudfunction.go
"React" to job opportunities on label added event. This allows users to trigger the same action (add to job board) on their own. 
Next, we need to react to the removal event.
> refactor: handle job opportunities on label add

- cloudfunctions/candidate_gmail_label_changes/cloudfunction.go
A regression after moving the parse logic to the label changes handler
> fix: do not parse verified jobs

- libs/src/db/schema.sql
- web/src/lib/supabase/client.ts
- web/src/routes/(app)/account/profile/+page.svelte
- web/src/routes/(app)/account/profile/+page.ts
- web/supabase/migrations/20230407012943_candidate_job_count_unverified.sql
Create a view for inbound job counts
> fix: use view for inbound job counts

- libs/src/db/schema.sql
- web/supabase/migrations/20230407020555_candidate_job_interest.sql
Fixes #210
Create a `candidate_job_interest` table and add it to the existing `vw_job_board` view
> feat: create candidate_job_interest table

- web/src/lib/pagination.ts
- web/src/routes/(app)/recruiter/(account)/jobs/+page.svelte
- web/src/routes/(app)/recruiter/(account)/jobs/+page.ts
- web/src/routes/(app)/recruiter/(account)/outbound/+page.svelte
- web/src/routes/(app)/recruiter/(account)/outbound/+page.ts
- Updates the remaining pagination use cases to the new pagination library
- Pagination library update in  https://github.com/shared-recruiting-co/shared-recruiting-co/pull/251
- PR should close out https://github.com/shared-recruiting-co/shared-recruiting-co/issues/202
- Additionally, this fixes an off-by-one bug introduced in the PR above
- This bug currently causes 11 results to be displayed instead of 10 in the table
@devstein
>  Update Remaining Pagination Use Cases

- web/package-lock.json
- web/package.json
This was preventing users from logging in 😅
Downgrading until this issue is closed https://github.com/supabase/auth-helpers/issues/545
> fix: downgrade supabase auth helper
